## 封装我们自己的SGD

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
m = 100000

x = np.random.normal(size=m)
y = 3. + 4. * x + np.random.normal(0.,3.,size=m)
X = x.reshape(-1,1)

In [3]:
X

array([[ 0.45202425],
       [ 0.88651083],
       [ 0.19860213],
       ...,
       [-0.73106153],
       [ 1.75898541],
       [-0.4217733 ]])

In [4]:
import sys
sys.path.append('..')

In [5]:
from ClassicIMPL.linear_regression.LinearRegression import LinearRegression

In [6]:
lin_reg = LinearRegression()
lin_reg.fit_bgd(X,y)

LinearRegression()

In [7]:
lin_reg.coef_

array([3.99504664])

In [8]:
lin_reg.intercept_

2.9822249955387616

In [9]:
lin_reg2 = LinearRegression()
lin_reg2.fit_sgd(X,y)

LinearRegression()

In [10]:
lin_reg2.coef_

array([3.9954347])

In [11]:
lin_reg2.intercept_

2.9826897834143304

## 使用我们自己的sgd

In [13]:
from sklearn import datasets

boston = datasets.load_boston()

X = boston.data
y = boston.target

X = X[y<50]
y = y[y<50]

In [15]:
from ClassicIMPL.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y)

In [16]:
from sklearn.preprocessing import StandardScaler

In [43]:
SS = StandardScaler()
SS.fit(X_train)

X_train_s = SS.transform(X_train)
X_test_s = SS.transform(X_test)

In [31]:
%time
lin_reg = LinearRegression()
lin_reg.fit_bgd(X_train_s,y_train)
lin_reg.score(X_test,y_test)

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.53 µs


0.7564002439782536

In [34]:
%time
lin_reg = LinearRegression()
lin_reg.fit_sgd(X_train_s,y_train,n_iters=40)
lin_reg.score(X_test_s,y_test)

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.53 µs


0.7532773009814785

In [38]:
%time
lin_reg = LinearRegression()
lin_reg.fit_sgd(X_train_s,y_train,n_iters=100)
lin_reg.score(X_test_s,y_test)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 4.53 µs


0.7533201987344528

## skiclearn中的SGD

In [39]:
from sklearn.linear_model import SGDRegressor

In [40]:
sgdr = SGDRegressor()

In [45]:
sgdr.fit(X_train_s,y_train)

/A/develop/ide/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDRegressor in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


SGDRegressor(alpha=0.0001, average=False, early_stopping=False, epsilon=0.1,
       eta0=0.01, fit_intercept=True, l1_ratio=0.15,
       learning_rate='invscaling', loss='squared_loss', max_iter=None,
       n_iter=None, n_iter_no_change=5, penalty='l2', power_t=0.25,
       random_state=None, shuffle=True, tol=None, validation_fraction=0.1,
       verbose=0, warm_start=False)

In [46]:
sgdr.score(X_test_s,y_test)

0.7680191824752224

In [48]:
sgdr = SGDRegressor(n_iter=50)
sgdr.fit(X_train_s,y_train)
sgdr.score(X_test_s,y_test)

/A/develop/ide/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:152: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)


0.7527763004775359