## 实现混淆矩阵，精准率和召回率

In [2]:
import numpy as np
from sklearn import datasets

In [4]:
digits = datasets.load_digits()
X=digits.data
y=digits.target.copy()

In [5]:
y[y!=9]=0
y[y==9]=1

In [6]:
y

array([0, 0, 0, ..., 0, 1, 0])

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y)

In [19]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train,y_train)
log_reg.score(X_test,y_test)

/A/develop/ide/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.9733333333333334

In [20]:
y_predict = log_reg.predict(X_test)

In [12]:
def TN(y_true,y_predict):
    assert len(y_true) == len(y_predict)
    return np.sum((y_true == 0) & (y_predict == 0))

In [13]:
def FP(y_true,y_predict):
    assert len(y_true) == len(y_predict)
    return np.sum((y_true == 0) & (y_predict == 1))

In [14]:
def FN(y_true,y_predict):
    assert len(y_true) == len(y_predict)
    return np.sum((y_true == 1) & (y_predict == 0))

In [16]:
def TP(y_true,y_predict):
    assert len(y_true) == len(y_predict)
    return np.sum((y_true == 1) & (y_predict == 1))

In [18]:
def confusion_matrix(y_true, y_predict):
    return np.array(
        [
        [TN(y_true,y_predict),FP(y_true,y_predict)],
        [FN(y_true,y_predict),TP(y_true,y_predict)]
        ]
    )
confusion_matrix(y_test,y_predict)

array([[396,   8],
       [  4,  42]])

In [21]:
def precision_score(y_true,y_predict):
    tp = TP(y_true, y_predict)
    fp = FP(y_true, y_predict)
    try:
        return tp / (tp + fp)
    except:
        return 0.0

In [22]:
precision_score(y_test,y_predict)

0.84

In [34]:
def recall_score(y_true, y_predict):
    fn = FN(y_true, y_predict)
    tp = TP(y_true, y_predict)
    try:
        return tp/(fn+tp)
    except:
        return 0.0
    
recall_score(y_test,y_predict)

0.9130434782608695

## scikit-learn中的混淆矩阵，精准率和召回率

In [26]:
from sklearn.metrics import confusion_matrix

In [27]:
confusion_matrix(y_test,y_predict)

array([[396,   8],
       [  4,  42]])

In [28]:
from sklearn.metrics import precision_score

In [30]:
precision_score(y_test,y_predict)

0.84

In [31]:
from sklearn.metrics import recall_score

In [32]:
recall_score(y_test,y_predict)

0.9130434782608695