## 精准度和召回率的平衡

In [1]:
from sklearn import datasets

digits = datasets.load_digits()
X = digits.data
y = digits.target.copy()

y[digits.target==9] = 1
y[digits.target!=9] = 0

In [2]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_predict = log_reg.predict(X_test)

/A/develop/ide/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [3]:
from sklearn.metrics import f1_score

In [5]:
f1_score(y_pred=y_predict,y_true=y_test)

0.8674698795180723

In [6]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_predict)


array([[403,   2],
       [  9,  36]])

In [7]:
from sklearn.metrics import precision_score

precision_score(y_test, y_predict)

0.9473684210526315

In [8]:
from sklearn.metrics import recall_score

recall_score(y_test, y_predict)

0.8

In [11]:
log_reg.decision_function(X_test)[:10]

array([-22.05700185, -33.02943631, -16.21335414, -80.37912074,
       -48.25121102, -24.54004847, -44.39161228, -25.0429358 ,
        -0.97827574, -19.71740779])

In [13]:
log_reg.decision_function(X_test)[:10]

array([-22.05700185, -33.02943631, -16.21335414, -80.37912074,
       -48.25121102, -24.54004847, -44.39161228, -25.0429358 ,
        -0.97827574, -19.71740779])

In [14]:
y_predict[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
decision_scores = log_reg.decision_function(X_test)

In [20]:
import numpy as np

In [21]:
y_predict2 = np.array(decision_scores >= 5,dtype=int)

In [22]:
confusion_matrix(y_test,y_predict2)

array([[404,   1],
       [ 21,  24]])

In [23]:
recall_score(y_test,y_predict2)

0.5333333333333333

In [24]:
precision_score(y_test,y_predict2)

0.96