In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import load_boston
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

boston = load_boston()
X,y = boston.data,boston.target
X_train,X_test,y_train,y_test= train_test_split(X,y)
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [4]:
# mean square method 均方误差
def mse(y, y_predict):
    y = np.array(y)
    y_predict = np.array(y_predict)
    return (y_predict - y) ** 2

def mse(X,theta,y):
    return mse(y, X.dot(theta.T))

In [5]:
# least square method 最小二乘法
def lsm(X , y):
    '''
    return (w,b)
    '''
    X = np.array(X)
    y = np.array(y)
    X_f = np.c_[X,np.ones(X.shape[0])]
    wb = np.linalg.inv(X_f.T.dot(X_f)).dot(X_f.T.dot(y))
    return (wb[:-1],wb[-1])

def test_lsm():
    print((lr.coef_,lr.intercept_))
    print(lsm(X_train,y_train))

test_lsm()

(array([-9.28067693e-02,  4.70201395e-02,  1.75098626e-02,  2.78737088e+00,
       -2.12542949e+01,  3.08353709e+00,  9.43648010e-03, -1.56107703e+00,
        3.02242419e-01, -1.12779476e-02, -1.08151858e+00,  7.63363229e-03,
       -5.79016807e-01]), 45.93619824514016)
(array([-9.28067693e-02,  4.70201395e-02,  1.75098626e-02,  2.78737088e+00,
       -2.12542949e+01,  3.08353709e+00,  9.43648010e-03, -1.56107703e+00,
        3.02242419e-01, -1.12779476e-02, -1.08151858e+00,  7.63363229e-03,
       -5.79016807e-01]), 45.93619824510188)


In [29]:
# 梯度向量
def gradient(X, y, theta):
    return (X.T.dot(X.dot(theta.T) - y))* 2. /len(y)

# 梯度下降 对波士顿房价发散.
def gradient_descent(
    X
    , y
    , theta = np.zeros(X.shape[1] + 1)
    , alpha= 0.000001
    , epsilon=1e-8
    , max_iter = 1e5
):
    X_ = np.c_[X , np.ones(X.shape[0])]
    #print(X_)
    iters = 0
    while(iters < max_iter):
        old_theta = theta
        grad = gradient(X_,y,theta)
        #print(theta)
        theta = theta - alpha * grad
        if(np.all(np.absolute(theta - old_theta) < epsilon)):
            break
        iters += 1
    return (theta[:-1],theta[-1])
#theta=(w,b)
theta  = gradient_descent(X_train,y_train)
# 此结果发散 ? Todo ?
print(theta)
print((lr.coef_,lr.intercept_))

(array([-0.05010703,  0.10462091, -0.05946112,  0.07211674,  0.0359923 ,
        0.90923614,  0.11698025,  0.04396554,  0.07883388, -0.003015  ,
        0.51469954,  0.02592524, -0.83450718]), 0.08805568196671718)
(array([-9.28067693e-02,  4.70201395e-02,  1.75098626e-02,  2.78737088e+00,
       -2.12542949e+01,  3.08353709e+00,  9.43648010e-03, -1.56107703e+00,
        3.02242419e-01, -1.12779476e-02, -1.08151858e+00,  7.63363229e-03,
       -5.79016807e-01]), 45.93619824514016)
