## 实现我们自己的LinearRegression

In [1]:
import numpy as np
from sklearn import datasets

In [2]:
boston = datasets.load_boston()

X = boston.data
y = boston.target

X = X[y < 50]
y = y[y < 50]

In [3]:
X.shape

(490, 13)

In [4]:
import sys
sys.path.append('..')

In [5]:
from ClassicIMPL.model_selection import train_test_split

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y)

In [7]:
len(X_train)

392

In [8]:
X_train.shape

(392, 13)

In [9]:
np.ones((len(X_train),1)) # 一列的元组

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [10]:
[np.ones((len(X_train),1))]

[array([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
      

In [11]:
[np.ones((len(X_train),1)),X_train]

[array([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
      

In [12]:
X_b = np.hstack([np.ones((len(X_train), 1)), X_train]) #将一列全都是1的向量添加到矩阵中,X_b, 添加的这一列是常数列
X_b

array([[1.00000e+00, 2.98500e-02, 0.00000e+00, ..., 1.87000e+01,
        3.94120e+02, 5.21000e+00],
       [1.00000e+00, 1.43200e-02, 1.00000e+02, ..., 1.51000e+01,
        3.92900e+02, 3.95000e+00],
       [1.00000e+00, 3.32105e+00, 0.00000e+00, ..., 1.47000e+01,
        3.96900e+02, 2.68200e+01],
       ...,
       [1.00000e+00, 3.03470e-01, 0.00000e+00, ..., 1.96000e+01,
        3.96900e+02, 6.15000e+00],
       [1.00000e+00, 3.42700e-02, 0.00000e+00, ..., 2.02000e+01,
        3.96900e+02, 9.80000e+00],
       [1.00000e+00, 6.58800e-02, 0.00000e+00, ..., 1.78000e+01,
        3.95560e+02, 7.56000e+00]])

In [13]:
l1 = [1,2,3,4,5,6,7,8,9]

In [14]:
np.hstack(l1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
theta = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y_train) # 线性数学公式直接求参数
theta

array([ 3.58309349e+01, -1.14542082e-01,  3.00123479e-02, -2.11932060e-02,
        2.16669339e-01, -1.45212272e+01,  3.44304244e+00, -9.78496777e-03,
       -1.15749384e+00,  2.92210227e-01, -1.48128293e-02, -8.78751699e-01,
        7.41581979e-03, -4.08473158e-01])

In [16]:
theta[0]# 截距

35.830934878801806

In [17]:
theta[1:]# 系数

array([-1.14542082e-01,  3.00123479e-02, -2.11932060e-02,  2.16669339e-01,
       -1.45212272e+01,  3.44304244e+00, -9.78496777e-03, -1.15749384e+00,
        2.92210227e-01, -1.48128293e-02, -8.78751699e-01,  7.41581979e-03,
       -4.08473158e-01])

In [18]:
from ClassicIMPL.linearRegression.LinearRegression import LinearRegression

In [19]:
reg = LinearRegression()

In [20]:
reg.fit_normal(X_train,y_train)

LinearRegression()

In [21]:
reg.coef_

array([-1.14542082e-01,  3.00123479e-02, -2.11932060e-02,  2.16669339e-01,
       -1.45212272e+01,  3.44304244e+00, -9.78496777e-03, -1.15749384e+00,
        2.92210227e-01, -1.48128293e-02, -8.78751699e-01,  7.41581979e-03,
       -4.08473158e-01])

In [22]:
reg.intercept_

35.830934878801806

In [23]:
reg.score(X_test,y_test)

0.7735907952475756