In [1]:
from sklearn import datasets
digits = datasets.load_digits()
X_digits = digits.data
y_digits = digits.target

In [6]:
from sklearn.svm import SVC
svc = SVC(C=1,kernel='linear')
svc.fit(X_digits[:-100],y_digits[:-100]).score(X_digits[-100:],y_digits[-100:])

0.98

In [7]:
import numpy as np

In [11]:
X_digits.shape

(1797, 64)

In [9]:
X_folds = np.array_split(X_digits,3)

In [18]:
y_folds = np.array_split(y_digits,3)

In [17]:
X_folds

[array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  5., ..., 16., 11.,  2.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 12.,  0.,  0.]]),
 array([[ 0.,  0.,  1., ..., 16., 16.,  8.],
        [ 0.,  0., 10., ..., 16., 16.,  9.],
        [ 0.,  0.,  6., ..., 16., 15.,  3.],
        ...,
        [ 0.,  1., 13., ...,  0.,  0.,  0.],
        [ 0.,  1.,  7., ..., 12.,  2.,  0.],
        [ 0.,  0., 13., ...,  0.,  0.,  0.]]),
 array([[ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  7., ...,  8.,  0.,  0.],
        [ 0.,  0., 12., ...,  0.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]])]

In [14]:
X_folds[0][0].size

64

In [20]:
y_folds[0].shape

(599,)

In [21]:
y_folds[1].shape

(599,)

In [28]:
list(X_folds) == X_folds

True

In [32]:
scores=[]
for k in range(3):
    X_train = list(X_folds)
    X_test = X_train.pop(k)
    X_train =np.concatenate(X_train)
    y_train = list(y_folds)
    y_test = y_train.pop(k)
    y_train  = np.concatenate(y_train)
    scores.append(svc.fit(X_train,y_train).score(X_test,y_test))

In [33]:
scores

[0.9348914858096828, 0.9565943238731218, 0.9398998330550918]

In [34]:
from sklearn.model_selection import KFold,cross_val_score

In [36]:
X = ["a", "a", "b", "c", "c", "c"]
kFold = KFold(n_splits=3)

for train_indices , test_indices in kFold.split(X):
    print('Train: %s | test: %s' % (train_indices, test_indices))

Train: [2 3 4 5] | test: [0 1]
Train: [0 1 4 5] | test: [2 3]
Train: [0 1 2 3] | test: [4 5]


In [38]:
[svc.fit(X_digits[ti],y_digits[ti]).score(X_digits[tei],y_digits[tei]) for ti,tei in kFold.split(X_digits)]

[0.9348914858096828, 0.9565943238731218, 0.9398998330550918]

In [41]:
cross_val_score(svc,X_digits,y_digits,cv=kFold,scoring='precision_macro')

array([0.93969761, 0.95911415, 0.94041254])

In [42]:
from sklearn.model_selection import GridSearchCV,cross_val_score

In [44]:
Cs = np.logspace(-6,-1,10)
Cs

array([1.00000000e-06, 3.59381366e-06, 1.29154967e-05, 4.64158883e-05,
       1.66810054e-04, 5.99484250e-04, 2.15443469e-03, 7.74263683e-03,
       2.78255940e-02, 1.00000000e-01])

In [50]:
clf = GridSearchCV(estimator=svc,param_grid=dict(C=Cs),n_jobs=-1)
clf.fit(X_digits[:-100],y_digits[:-100])

/A/develop/ide/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid={'C': array([1.00000e-06, 3.59381e-06, 1.29155e-05, 4.64159e-05, 1.66810e-04,
       5.99484e-04, 2.15443e-03, 7.74264e-03, 2.78256e-02, 1.00000e-01])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [52]:
clf.best_estimator_.score(X_digits[-100:],y_digits[-100:])

0.98

In [53]:
from sklearn import linear_model,datasets

lasso = linear_model.LassoCV()
diabetes = datasets.load_diabetes()
X_diabetes = diabetes.data
y_diabetes = diabetes.target
lasso.fit(X_diabetes,y_diabetes)
lasso.alpha_

/A/develop/ide/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


0.012291895087486161